# Generated by Django 4.0.1 on 2022-01-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_id', models.IntegerField(primary_key=b'I01\n', serialize=False)),
                ('Emp_fname', models.CharField(max_length=30)),
                ('Emp_lname', models.CharField(max_length=30)),
                ('Emp_sex', models.CharField(max_length=10)),
                ('Emp_email', models.EmailField(max_length=30)),
                ('Emp_password', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner')),
            ],
        ),
    ]
