# Generated by Django 4.0.1 on 2022-01-27 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_employee_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Cust_fname', models.CharField(max_length=30)),
                ('Cust_lname', models.CharField(max_length=30)),
                ('Cust_sex', models.CharField(max_length=10)),
                ('Cust_email', models.EmailField(max_length=30)),
                ('Cust_password', models.CharField(max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner')),
            ],
        ),
    ]
