# Generated by Django 4.0.1 on 2022-01-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Order_quantity', models.IntegerField()),
                ('Order_name', models.CharField(max_length=30)),
                ('Order_description', models.CharField(max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner')),
            ],
        ),
    ]
