# Generated by Django 4.0.1 on 2022-01-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('Stock_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Stock_name', models.CharField(max_length=30)),
                ('Stock_quantity', models.CharField(max_length=30)),
                ('Stock_description', models.CharField(max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner')),
            ],
        ),
    ]
