# Generated by Django 4.0.1 on 2022-01-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_alter_owner_owner_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_inventory_city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_inventory_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_lname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
